import Image, { type ImageProps } from "next/image";
import sizes from "@/lib/assets.json";

type Props = Omit<ImageProps, "src" | "width" | "height"> & { src: string };

/** next/image with intrinsic sizes looked up from lib/assets.json (generated by scripts/assets.py). */
export default function Img({ src, alt, sizes: s = "(max-width: 800px) 90vw, 600px", ...rest }: Props) {
  const [width, height] = (sizes as Record<string, number[]>)[src] ?? [800, 800];
  return <Image src={src} alt={alt} width={width} height={height} sizes={s} {...rest} />;
}
